-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE DATABASE building_measurement
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'en_US.UTF-8'
    LC_CTYPE = 'en_US.UTF-8'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;

GRANT TEMPORARY, CONNECT ON DATABASE building_measurement TO PUBLIC;

GRANT ALL ON DATABASE building_measurement TO bigg;

GRANT ALL ON DATABASE building_measurement TO postgres;


CREATE TABLE IF NOT EXISTS public.company
(
    name character varying,
    id integer NOT NULL,
    created_date timestamp with time zone,
    last_updated timestamp with time zone,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.site
(
    name character varying,
    id integer,
    created_date timestamp with time zone,
    last_updated timestamp with time zone,
    company_id integer,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.building
(
    name character varying,
    id integer,
    created_date timestamp with time zone,
    last_updated timestamp with time zone,
    site_id integer,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.zone
(
    name character varying,
    id integer,
    created_date timestamp with time zone,
    last_updated timestamp with time zone,
    building_id integer,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.building_space
(
    name character varying,
    id integer,
    created_date timestamp with time zone,
    last_updated timestamp with time zone,
    zone_id integer,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.sensor
(
    name character varying,
    id integer,
    created_date timestamp with time zone,
    last_updated timestamp with time zone,
    measurement character varying,
    building_space_id integer,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.site
    ADD CONSTRAINT company_id_fk FOREIGN KEY (company_id)
    REFERENCES public.company (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.building
    ADD CONSTRAINT site_id_fk FOREIGN KEY (site_id)
    REFERENCES public.site (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.zone
    ADD CONSTRAINT building_id_fk FOREIGN KEY (building_id)
    REFERENCES public.building (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.building_space
    ADD CONSTRAINT zone_id_fk FOREIGN KEY (zone_id)
    REFERENCES public.zone (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.sensor
    ADD CONSTRAINT building_space_fk_id FOREIGN KEY (building_space_id)
    REFERENCES public.building_space (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;

END;
